version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: teampulse-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    container_name: teampulse-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  mongo-express:
    image: mongo-express:1.0.0
    container_name: teampulse-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ""
      ME_CONFIG_MONGODB_ADMINPASSWORD: ""
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    ports:
      - "8081:8081"
    depends_on:
      - mongo

volumes:
  mongo-data:
